### ISSUE TITLE
net::ERR_CONNECTION_REFUSED

### ISSUE THREAD

**Issue by khatiwadaaj** [bradtraversy/mongochat#2]
polling-xhr.js:264 GET http://localhost/socket.io/?EIO=3&transport=polling&t=MO9LTIe net::ERR_CONNECTION_REFUSED

I followed this tutorial from start to end by myself and end up with this issue. And again I cloned this repo to check if I was missing something and ran up to the same kind of error. Somewhere in the github I read that it is a chrome bug.

**Comment by behimar** [comment]
i have the same problem... and when mongo find execute the server freezes

**Comment by bouchrabelmehdi** [comment]
Please did you succeed in making the app work in the client side? If yes, how did you do so?
Thank you so much in advance for your answer.

**Comment by trautmaa** [comment]
This is related to using mongodb version 3

**Comment by trautmaa** [comment]
Upgrade to Mongo3 then server.js:

`const mongo = require('mongodb').MongoClient;
const socketClient = require('socket.io').listen(4000).sockets;

const dbname = 'mongochat'

// Connect to mongo
mongo.connect('mongodb://127.0.0.1/' + dbname, function (err, client) {
    if (err) {
        throw err;
    }
    var db = client.db(dbname);

    console.log('MongoDB connected...');

    // Connect to Socket.io
    socketClient.on('connection', function (socket) {
        let chat = db.collection('chats');

        // Create function to send status
        sendStatus = function (s) {
            socket.emit('status', s);
        }

        // Get chats from mongo collection
        chat.find().limit(100).sort({ _id: 1 }).toArray(function (err, res) {
            if (err) {
                throw err;
            }

            // Emit the messages
            socket.emit('output', res);
        });

        // Handle input events
        socket.on('input', function (data) {
            let name = data.name;
            let message = data.message;

            // Check for name and message
            if (name == '' || message == '') {
                // Send error status
                sendStatus('Please enter a name and message');
            } else {
                // Insert message
                chat.insert({ name: name, message: message }, function () {
                    socketClient.emit('output', [data]);

                    // Send status object
                    sendStatus({
                        message: 'Message sent',
                        clear: true
                    });
                });
            }
        });

        // Handle clear
        socket.on('clear', function (data) {
            // Remove all chats from collection
            chat.remove({}, function () {
                // Emit cleared
                socket.emit('cleared');
            });
        });
    });
});`

**Comment by khatiwadaaj** [comment]
...
